apiVersion: v1
kind: Service
metadata:
  name: {{ include "asiot.fullname" . }}
  labels:
    {{- include "asiot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "asiot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
